"""Regression guards for repository-structure problems found in review."""
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def test_every_python_package_dir_has_dunder_init():
    """`_init_py` (single underscores) silently breaks find_packages()/wheels."""
    missing = [str(d.relative_to(ROOT)) for d in (ROOT / "src" / "atlas").rglob("*")
               if d.is_dir() and d.name != "__pycache__" and any(d.glob("*.py"))
               and not (d / "__init__.py").exists()]
    assert not missing, f"Missing __init__.py in: {missing}"
    assert (ROOT / "src" / "atlas" / "__init__.py").exists()


def test_no_mangled_or_generated_files_tracked():
    bad = [str(p.relative_to(ROOT)) for p in ROOT.rglob("*")
           if p.is_file() and ".git" not in p.parts
           and (p.name in ("_init_py", "_init_lean", ".gitkpeep")
                or p.parent.name == "_pycache_")]
    assert not bad, f"Mangled file names found: {bad}"


def test_lakefile_has_top_level_name_and_root_module():
    lake = (ROOT / "formal" / "lean" / "lakefile.toml").read_text(encoding="utf-8")
    code = "\n".join(l for l in lake.splitlines() if not l.strip().startswith("#"))
    assert "[package]" not in code, "Lake rejects a [package] table (missing required key: name)"
    assert any(l.startswith("name") for l in code.splitlines()), "top-level `name` missing"
    assert (ROOT / "formal" / "lean" / "ErdosAtlas.lean").is_file(), "lean_lib root module missing"
    assert (ROOT / "formal" / "lean" / "Main.lean").is_file(), "Main.lean (case-sensitive) missing"


def test_lake_manifest_is_not_a_placeholder():
    m = ROOT / "formal" / "lean" / "lake-manifest.json"
    if m.exists():
        text = m.read_text(encoding="utf-8")
        assert "PLACEHOLDER" not in text and "__WARNING__" not in text, \
            "lake-manifest.json must be generated by `lake update`, not hand-written"


def test_results_sha256sums_match():
    d = ROOT / "results" / "latest"
    sums = d / "SHA256SUMS"
    if not sums.exists():
        return
    for line in sums.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        expected, name = line.split(None, 1)
        actual = hashlib.sha256((d / name.strip()).read_bytes()).hexdigest()
        assert actual == expected, f"{name}: checksum mismatch (rebuild with `make manifest`)"
